/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author merin
 */
import java.awt.CardLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Booking extends javax.swing.JFrame {

    Connection connect;
    CardLayout cardlayout;
    String s, driver,drivername=null;
    int f = 0, bkid = 0;
    DefaultTableModel dbtable2;
    DefaultTableModel model;
    String seldriver;
    String frlocation, tolocation, pre, date, string_time;

    public Booking(String userid) {
        s = userid;
        initComponents();
        cardlayout = (CardLayout) (jPanel2.getLayout());
        connect = dbms.dbconnect();
        cardlayout.show(jPanel2, "profile");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        feedback = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        mobile_no = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        wallet_bal = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        wallet_bal1 = new javax.swing.JLabel();
        username1 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        mobile_no1 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        thankyou = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        review = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        Destination = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        booking = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        nobooking = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerLocation(250);
        jSplitPane1.setDividerSize(1);
        jSplitPane1.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Hello, User");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 0));
        jButton1.setText("Profile");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 0));
        jButton2.setText("Review Booking");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 0));
        jButton3.setText("Booking History");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 0));
        jButton4.setText("Feedback");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 0));
        jButton5.setText("Book My Cab");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 0));
        jButton9.setText("Logout");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.CardLayout());

        feedback.setLayout(null);

        jLabel35.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel35.setText("Rate your Journey..");
        feedback.add(jLabel35);
        jLabel35.setBounds(25, 40, 306, 45);

        jLabel36.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel36.setText("Your suggestions");
        feedback.add(jLabel36);
        jLabel36.setBounds(25, 300, 197, 46);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        feedback.add(jTextField4);
        jTextField4.setBounds(227, 308, 371, 93);

        jLabel37.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel37.setText("Driver Rating ");
        feedback.add(jLabel37);
        jLabel37.setBounds(25, 128, 197, 46);

        jLabel38.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel38.setText("Any comments");
        feedback.add(jLabel38);
        jLabel38.setBounds(25, 183, 197, 46);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        feedback.add(jTextField5);
        jTextField5.setBounds(227, 130, 184, 46);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        feedback.add(jTextField6);
        jTextField6.setBounds(227, 197, 371, 93);

        jButton10.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        feedback.add(jButton10);
        jButton10.setBounds(311, 476, 148, 46);

        jLabel46.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        feedback.add(jLabel46);
        jLabel46.setBounds(0, 0, 1080, 859);

        jPanel2.add(feedback, "feedback");

        profile.setLayout(null);

        mobile_no.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        mobile_no.setText("Mobile No");
        profile.add(mobile_no);
        mobile_no.setBounds(20, 260, 190, 39);

        username.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        username.setText("Username");
        profile.add(username);
        username.setBounds(20, 128, 161, 43);

        wallet_bal.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        wallet_bal.setText("Wallet Balance");
        profile.add(wallet_bal);
        wallet_bal.setBounds(20, 317, 190, 39);

        name.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        name.setText("Name");
        profile.add(name);
        name.setBounds(20, 196, 190, 39);

        wallet_bal1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        profile.add(wallet_bal1);
        wallet_bal1.setBounds(474, 315, 230, 39);

        username1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        profile.add(username1);
        username1.setBounds(474, 132, 230, 39);

        name1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        profile.add(name1);
        name1.setBounds(475, 195, 229, 40);

        mobile_no1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        profile.add(mobile_no1);
        mobile_no1.setBounds(474, 257, 229, 40);

        jLabel45.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        profile.add(jLabel45);
        jLabel45.setBounds(0, 0, 1238, 859);

        jPanel2.add(profile, "profile");

        thankyou.setLayout(null);

        jLabel39.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel39.setText("Thankyou for your feedback..");
        thankyou.add(jLabel39);
        jLabel39.setBounds(27, 39, 366, 46);

        jLabel44.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        thankyou.add(jLabel44);
        jLabel44.setBounds(0, 0, 1238, 859);

        jPanel2.add(thankyou, "thankyou");

        review.setDoubleBuffered(false);
        review.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Booking Time");
        review.add(jLabel1);
        jLabel1.setBounds(107, 165, 184, 39);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Booking Date");
        review.add(jLabel2);
        jLabel2.setBounds(107, 119, 184, 39);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Estimated distance");
        review.add(jLabel3);
        jLabel3.setBounds(107, 253, 184, 39);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Booking ID");
        review.add(jLabel4);
        jLabel4.setBounds(107, 21, 184, 39);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("Driver Contact ");
        review.add(jLabel5);
        jLabel5.setBounds(107, 299, 184, 39);

        jLabel13.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel13.setText("Car Model");
        review.add(jLabel13);
        jLabel13.setBounds(107, 345, 184, 39);

        jLabel14.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel14.setText("Cab Fare");
        review.add(jLabel14);
        jLabel14.setBounds(107, 391, 184, 39);

        jLabel15.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel15.setText("Cab Driver");
        review.add(jLabel15);
        jLabel15.setBounds(107, 67, 184, 39);

        Destination.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        Destination.setText("Destination");
        review.add(Destination);
        Destination.setBounds(107, 483, 184, 39);

        jButton8.setBackground(new java.awt.Color(204, 204, 204));
        jButton8.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jButton8.setText("Cancel Booking");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        review.add(jButton8);
        jButton8.setBounds(968, 601, 244, 36);
        review.add(jLabel16);
        jLabel16.setBounds(1034, 529, 192, 41);
        review.add(jLabel18);
        jLabel18.setBounds(1034, 21, 192, 39);
        review.add(jLabel19);
        jLabel19.setBounds(1034, 211, 192, 39);
        review.add(jLabel20);
        jLabel20.setBounds(1034, 67, 192, 39);
        review.add(jLabel21);
        jLabel21.setBounds(1034, 119, 192, 39);
        review.add(jLabel22);
        jLabel22.setBounds(1034, 299, 192, 39);
        review.add(jLabel23);
        jLabel23.setBounds(1034, 345, 192, 39);
        review.add(jLabel24);
        jLabel24.setBounds(1034, 437, 192, 39);
        review.add(jLabel25);
        jLabel25.setBounds(1034, 165, 192, 39);

        jLabel29.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel29.setText("Mode of Payment");
        review.add(jLabel29);
        jLabel29.setBounds(107, 529, 184, 39);

        jLabel30.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel30.setText("PickUp");
        review.add(jLabel30);
        jLabel30.setBounds(107, 437, 184, 39);
        review.add(jLabel31);
        jLabel31.setBounds(1034, 483, 192, 39);
        review.add(jLabel32);
        jLabel32.setBounds(1034, 391, 192, 39);

        jLabel17.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel17.setText("Departure Time");
        review.add(jLabel17);
        jLabel17.setBounds(107, 211, 184, 39);
        review.add(jLabel33);
        jLabel33.setBounds(1034, 253, 192, 39);

        jLabel43.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        review.add(jLabel43);
        jLabel43.setBounds(0, 0, 1238, 859);

        jPanel2.add(review, "review");

        booking.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel7.setText("Drop");
        booking.add(jLabel7);
        jLabel7.setBounds(29, 112, 145, 35);

        jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel8.setText("Pickup");
        booking.add(jLabel8);
        jLabel8.setBounds(29, 64, 145, 35);

        jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel9.setText("When");
        booking.add(jLabel9);
        jLabel9.setBounds(29, 154, 145, 35);

        jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel10.setText("Time");
        booking.add(jLabel10);
        jLabel10.setBounds(447, 280, 145, 35);

        jLabel11.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel11.setText("Estimated Distance(kms)");
        booking.add(jLabel11);
        jLabel11.setBounds(29, 196, 316, 35);

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setEditable(true);
        jComboBox1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Now", "Schedule Later" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        booking.add(jComboBox1);
        jComboBox1.setBounds(986, 154, 148, 34);

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setEditable(true);
        jComboBox2.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kollam", "Trivandrum", "Pathnamthitta", "Idukki", "Thrissur", "Ernakulam", "Malappuram", "Kozhikode" }));
        jComboBox2.setBorder(null);
        booking.add(jComboBox2);
        jComboBox2.setBounds(986, 112, 148, 34);

        jComboBox4.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox4.setEditable(true);
        jComboBox4.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kollam", "Trivandrum", "Pathnamthitta", "Idukki", "Thrissur", "Ernakulam", "Malappuram", "Kozhikode" }));
        jComboBox4.setBorder(null);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        booking.add(jComboBox4);
        jComboBox4.setBounds(986, 60, 148, 34);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        booking.add(jTextField2);
        jTextField2.setBounds(986, 285, 148, 33);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        booking.add(jTextField3);
        jTextField3.setBounds(265, 285, 148, 33);

        jLabel12.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel12.setText("Departure");
        booking.add(jLabel12);
        jLabel12.setBounds(29, 280, 145, 35);

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton6.setText("Search Cabs");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        booking.add(jButton6);
        jButton6.setBounds(500, 360, 139, 33);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Driver name", "Car Model", "User Rating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(102, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        booking.add(jScrollPane1);
        jScrollPane1.setBounds(210, 410, 744, 175);

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jButton7.setText("Confirm Booking");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        booking.add(jButton7);
        jButton7.setBounds(490, 600, 176, 33);
        booking.add(jLabel27);
        jLabel27.setBounds(986, 238, 148, 35);

        jLabel34.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel34.setText("Estimated Fare");
        booking.add(jLabel34);
        jLabel34.setBounds(29, 238, 188, 35);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        booking.add(jTextField1);
        jTextField1.setBounds(986, 199, 148, 32);

        jLabel42.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        booking.add(jLabel42);
        jLabel42.setBounds(0, 0, 1238, 859);

        jPanel2.add(booking, "booking");

        nobooking.setLayout(null);

        jLabel28.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel28.setText("Sorry, you have no bookings...");
        nobooking.add(jLabel28);
        jLabel28.setBounds(39, 53, 373, 37);

        jLabel41.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        nobooking.add(jLabel41);
        jLabel41.setBounds(0, 0, 1238, 859);

        jPanel2.add(nobooking, "nobooking");

        history.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BookingID", "BookingDate", "Destination", "PickUp", "BookingTime", "CabDriver", "Estimated kms", "DepartureTime", "CabFare", "ModeOfPayment"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        history.add(jScrollPane2);
        jScrollPane2.setBounds(10, 150, 1214, 369);

        jLabel26.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel26.setText("Show By");
        history.add(jLabel26);
        jLabel26.setBounds(360, 50, 126, 27);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Month" }));
        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        history.add(jComboBox3);
        jComboBox3.setBounds(530, 60, 99, 27);

        jLabel40.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\screenshot_2.png")); // NOI18N
        history.add(jLabel40);
        jLabel40.setBounds(0, 0, 1238, 859);

        jPanel2.add(history, "history");

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1480, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        setSize(new java.awt.Dimension(1494, 689));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cardlayout.show(jPanel2, "profile");
        String dbname = null;
        String dbmobile_no = null;
        int dbwallet_bal = 0;
        try {
            String query1 = "select * from users where username=?";
            PreparedStatement ps = connect.prepareStatement(query1);
            ps.setString(1, s);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                dbname = rs.getString("name");
                dbmobile_no = rs.getString("mobile_no");
                dbwallet_bal = rs.getInt("wallet_bal");
            }
            username1.setText(s);
            name1.setText(dbname);
            mobile_no1.setText(dbmobile_no);
            wallet_bal1.setText(String.valueOf(dbwallet_bal));
            jLabel6.setText("Hello, " + dbname);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cardlayout.show(jPanel2, "booking");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (f == 1) {
            cardlayout.show(jPanel2, "review");
            String bookingid = null, bookingdate = null, bookingtime = null, departure = null, driver = null, contact = null;
            String mode = null, model = null, dbname = null, pickup = null, destination = null;
            int fare = 0, distance = 0;
            try {
                String query1 = "select * from bookings where bookingid=?";
                PreparedStatement ps = connect.prepareStatement(query1);
                System.out.println(bkid);
                ps.setInt(1, bkid);
                ResultSet rs = ps.executeQuery();
                System.out.println("faf");
                while (rs.next()) {
                    bookingid = rs.getString("bookingid");
                    bookingdate = rs.getString("bookingdate");
                    bookingtime = rs.getString("bookingtime");
                    departure = rs.getString("departure");
                    driver = rs.getString("driver");
                    mode = rs.getString("modeofpayment");
                    dbname = rs.getString("username");
                    pickup = rs.getString("pickup");
                    destination = rs.getString("destination");
                    fare = rs.getInt(7);
                    distance = rs.getInt(11);
                    //System.out.println("faf");
                }
                query1 = "select * from driver where name=?";
                ps = connect.prepareStatement(query1);
                ps.setString(1, driver);
                rs = ps.executeQuery();
                while (rs.next()) {
                    model = rs.getString("car_model");
                }
                query1 = "select * from users where name=?";
                ps = connect.prepareStatement(query1);
                ps.setString(1, driver);
                rs = ps.executeQuery();
                while (rs.next()) {
                    contact = rs.getString("mobile_no");
                }
                //System.out.println("faf");
                jLabel18.setText(bookingid);
                jLabel20.setText(driver);
                jLabel21.setText(bookingdate);
                jLabel25.setText(bookingtime);
                jLabel19.setText(departure);
                jLabel23.setText(model);
                jLabel22.setText(contact);
                jLabel16.setText(mode);
                jLabel31.setText(destination);
                jLabel24.setText(pickup);
                jLabel32.setText(String.valueOf(fare));
                jLabel33.setText(String.valueOf(distance));
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            cardlayout.show(jPanel2, "nobooking");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        cardlayout.show(jPanel2, "history");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed

    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        String bookingid = null, bookingdate = null, bookingtime = null, departure = null, driver = null, pickup = null;
        String mode = null, destination = null;
        String s1 = null;
        int fare = 0, distance = 0, r;
        LocalDate date = java.time.LocalDate.now();
        String str_date = date.toString();
        dbtable2 = (DefaultTableModel) jTable2.getModel();

        if (jComboBox3.getItemAt(jComboBox3.getSelectedIndex()) == "Date") {
            //System.out.println("fegvv");
            s1 = str_date.substring(8, 10);
            String ss = jComboBox3.getItemAt(jComboBox3.getSelectedIndex());
            r = dbtable2.getRowCount();
            for (int i = 0; i < r; i++) {
                if (r == 0) {
                    break;
                }
                dbtable2.removeRow(0);
            }
            try {

                System.out.println(s1);
                String query1 = "select * from bookings where username=?";
                PreparedStatement ps = connect.prepareStatement(query1);
                //System.out.println("evcsev");
                ps.setString(1, s);
                ResultSet rs = ps.executeQuery();
                //System.out.println("evcsev");
                while (rs.next()) {
                    System.out.println(rs.getString("bookingdate"));
                    if (!((rs.getString("bookingdate")).substring(0, 2)).equals(s1)) {
                        System.out.println(rs.getString("bookingdate").substring(0,2)+" "+s1);
                    } else {
                        bookingid = rs.getString("bookingid");
                        //System.out.println(bookingid);
                        bookingdate = rs.getString("bookingdate");
                        bookingtime = rs.getString("bookingtime");
                        departure = rs.getString("departure");
                        driver = rs.getString("driver");
                        //System.out.println(bookingtime+bookingdate+driver+departure);
                        pickup = rs.getString("pickup");
                        mode = rs.getString("modeofpayment");
                        //System.out.println(mode+pickup);
                        destination = rs.getString("destination");
                        distance = rs.getInt(11);
                        fare = rs.getInt(7);
                        //System.out.println(destination);

                        String tbdata[] = {bookingid, bookingdate, destination, pickup, bookingtime, driver, String.valueOf(distance), departure, String.valueOf(fare), mode};
                        dbtable2.addRow(tbdata);
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
                e.printStackTrace();
            }
        } else {
            System.out.println(str_date);
            s1 = str_date.substring(5, 7);
            r = dbtable2.getRowCount();
            for (int i = 0; i < r; i++) {
                if (r == 0) {
                    break;
                }
                dbtable2.removeRow(0);
            }
            try {
                String query1 = "select * from bookings where username=?";
                PreparedStatement ps = connect.prepareStatement(query1);
                ps.setString(1, s);
                ResultSet rs = ps.executeQuery();
                while (rs.next()) {
                    System.out.println(rs.getString("bookingdate"));
                    if (!((rs.getString("bookingdate")).substring(3, 5)).equals(s1)) {
                        System.out.println((rs.getString("bookingdate")).substring(3, 5) + " " + s1);
                    } else {
                        System.out.println("fcsd);");
                        bookingid = rs.getString("bookingid");
                        bookingdate = rs.getString("bookingdate");
                        bookingtime = rs.getString("bookingtime");
                        departure = rs.getString("departure");
                        driver = rs.getString("driver");
                        pickup = rs.getString("pickup");
                        mode = rs.getString("modeofpayment");
                        destination = rs.getString("destination");
                        distance = rs.getInt(11);
                        fare = rs.getInt(7);

                        String tbdata[] = {bookingid, bookingdate, destination, pickup, bookingtime, driver, String.valueOf(distance), departure, String.valueOf(fare), mode};
                        //dbtable2=(DefaultTableModel)jTable2.getModel();
                        dbtable2.addRow(tbdata);
                        System.out.println("fcsvsvd);");
                    }
                }
            } catch (Exception e) {
                System.out.println(e);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (f == 1) {
            cardlayout.show(jPanel2, "feedback");
        } else {
            cardlayout.show(jPanel2, "nobooking");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        float time = 0;
        int distance = Integer.parseInt(jTextField1.getText());
        int fare = distance * 50;
        jLabel27.setText(String.valueOf(fare));
        frlocation = (String) jComboBox4.getSelectedItem();
        tolocation = (String) jComboBox2.getSelectedItem();
        pre = (String) jComboBox1.getSelectedItem();
        date = jTextField3.getText();
        string_time = jTextField2.getText();
        if (string_time.equals("") && pre.equals("Now")) {

            LocalTime lt = java.time.LocalTime.now();
            string_time = lt.toString();
            string_time = string_time.substring(0, 5);
            string_time = string_time.replace(':', '.');
            System.out.println(string_time);
        }

        time = Float.parseFloat(string_time);
        System.out.println(time);

        try {
            PreparedStatement ps = connect.prepareStatement("select driver_id,model,user_rating from available where curr_loc=? and stime<? and ?<etime");
            ps.setString(1, frlocation);
            ps.setFloat(2, time);
            ps.setFloat(3, time);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                System.out.println(rs.getString(1));
                model.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }

        } catch (SQLException ex) {
            Logger.getLogger(Booking.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        f = 1;
        int base = 0;
        LocalTime time = java.time.LocalTime.now();
        String str_time = time.toString();
        str_time = str_time.substring(0, 5);
        DefaultTableModel table = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        PreparedStatement ps = null;
        String query1 = null;
        ResultSet rs = null;
        try {
            query1 = "select * from bookings";
            ps = connect.prepareStatement(query1);
            //ps.setString(1, (String)jTable1.getModel().getValueAt(0,0));
            rs = ps.executeQuery();
            while (rs.next()) {
                bkid = rs.getInt(1);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
        bkid = bkid + 1;

        try {

            query1 = "insert into bookings(bookingid,bookingdate,bookingtime,departure,driver,modeofpayment,cab_fare,username,pickup,destination,kms) values(?,?,?,?,?,?,?,?,?,?,?)";
            ps = connect.prepareStatement(query1);
            ps.setInt(1,bkid);
            ps.setString(8, s);
            drivername=table.getValueAt(row, 0).toString();
            ps.setString(5, drivername);
            ps.setString(2, jTextField3.getText());
            ps.setString(4, jTextField2.getText());
            ps.setString(9, jComboBox4.getItemAt(jComboBox4.getSelectedIndex()));
            ps.setString(10, jComboBox2.getItemAt(jComboBox2.getSelectedIndex()));
            ps.setInt(7, Integer.parseInt(jLabel27.getText()));
            ps.setString(6, "Cash");
            ps.setInt(11, Integer.parseInt(jTextField1.getText()));
            ps.setString(3, str_time);
            ps.execute();

            query1 = "select * from driver where name=?";
            ps = connect.prepareStatement(query1);
            ps.setString(1, (String) jTable1.getModel().getValueAt(0, 0));
            rs = ps.executeQuery();
            while (rs.next()) {
                base = rs.getInt(7);
            }

            base = base + Integer.parseInt(jLabel27.getText());
            int a = JOptionPane.showConfirmDialog(null, "Confirm Booking?");
            if (a == JOptionPane.YES_OPTION) {
                new payment(base, bkid, s).setVisible(true);
            } else {
            }
        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int a = JOptionPane.showConfirmDialog(null, "Are you sure?");
        if (a == JOptionPane.YES_OPTION) {
            try {
                String query1 = "delete from bookings where bookingid=?";
                PreparedStatement ps = connect.prepareStatement(query1);
                ps.setInt(1, bkid);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Booking Cancelled Successfully");
            } catch (SQLException ex) {
            }

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.setVisible(false);
        new login1().setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        String query1;
        PreparedStatement ps;
        ResultSet rs;
        int fid = 0, count = 0;
        float r = 0;
        try {
            query1 = "select * from feedbacks";
            ps = connect.prepareStatement(query1);
            //ps.setString(1, (String)jTable1.getModel().getValueAt(0,0));
            rs = ps.executeQuery();
            while (rs.next()) {
                fid = rs.getInt(1);
            }
            fid = fid + 1;
             
            System.out.println("review"+driver);
            query1 = "insert into feedbacks values(?,?,?,?,?,?)";
            ps = connect.prepareStatement(query1);
            ps.setInt(1, fid);
            ps.setString(2, s);
            ps.setString(3, drivername);
            ps.setString(4, jTextField6.getText());
            ps.setString(5, jTextField4.getText());
            ps.setFloat(6, Float.parseFloat(jTextField5.getText()));
            ps.execute();

            query1 = "select count(*) from bookings where drivername=?";
            ps = connect.prepareStatement(query1);
            ps.setString(1, drivername);
            rs = ps.executeQuery();
            while (rs.next()) {
                count = rs.getInt(1);
            }

            query1 = "select * from available where driver_id=?";
            ps = connect.prepareStatement(query1);
            ps.setString(1, drivername);
            rs = ps.executeQuery();
            while (rs.next()) {
                r = rs.getFloat(5);
            }

            r = (r * count + Float.parseFloat(jTextField5.getText())) / (count + 1);

            query1 = "update driver set rating=? where name=?";
            ps = connect.prepareStatement(query1);
            ps.setString(2, drivername);
            ps.setFloat(1, r);
            ps.executeUpdate();
             query1 = "update available set rating=? where driver_id=?";
            ps = connect.prepareStatement(query1);
            ps.setString(2, drivername);
            ps.setFloat(1, r);
            ps.executeUpdate();
        } catch (Exception e) {
            System.out.println(e);
        }
        cardlayout.show(jPanel2, "thankyou");
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Booking("amarami").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Destination;
    private javax.swing.JPanel booking;
    private javax.swing.JPanel feedback;
    private javax.swing.JPanel history;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel mobile_no;
    private javax.swing.JLabel mobile_no1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel name1;
    private javax.swing.JPanel nobooking;
    private javax.swing.JPanel profile;
    private javax.swing.JPanel review;
    private javax.swing.JPanel thankyou;
    private javax.swing.JLabel username;
    private javax.swing.JLabel username1;
    private javax.swing.JLabel wallet_bal;
    private javax.swing.JLabel wallet_bal1;
    // End of variables declaration//GEN-END:variables
}
