
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class login1 extends javax.swing.JFrame {
    Connection connect = null;
   int type;
    /**
     * Creates new form login1
     */
    public login1() {
        initComponents();
        connect = dbms.dbconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        signup = new javax.swing.JButton();
        pass1 = new javax.swing.JPasswordField();
        user = new javax.swing.JTextField();
        checkbox = new javax.swing.JCheckBox();
        login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.setFont(new java.awt.Font("Segoe Print", 3, 48)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Book My Cab");
        getContentPane().add(name);
        name.setBounds(130, 10, 442, 59);

        signup.setBackground(new java.awt.Color(0, 0, 0));
        signup.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        signup.setForeground(new java.awt.Color(255, 255, 0));
        signup.setText("Sign Up");
        signup.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup);
        signup.setBounds(400, 300, 160, 40);

        pass1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pass1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pass1FocusLost(evt);
            }
        });
        pass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass1ActionPerformed(evt);
            }
        });
        getContentPane().add(pass1);
        pass1.setBounds(200, 160, 300, 40);

        user.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        user.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userFocusLost(evt);
            }
        });
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(200, 100, 300, 40);

        checkbox.setBackground(new java.awt.Color(255, 255, 255));
        checkbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        checkbox.setText("Show password");
        checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxActionPerformed(evt);
            }
        });
        getContentPane().add(checkbox);
        checkbox.setBounds(280, 220, 160, 20);

        login.setBackground(new java.awt.Color(0, 0, 0));
        login.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 0));
        login.setText("Login");
        login.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(140, 300, 160, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\merin\\Documents\\NetBeansProjects\\JDBC-master\\src\\main\\java\\images\\about-taxi.png")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 740, 440);

        setSize(new java.awt.Dimension(750, 476));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxActionPerformed
        if(checkbox.isSelected()){
            pass1.setEchoChar((char)0);
        }else
        pass1.setEchoChar('*');
    }//GEN-LAST:event_checkboxActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        int check = 0;
        if(pass1.getPassword().length==0){
            JOptionPane.showMessageDialog(null, "Enter Valid Password");
        }
        else if(user.getText().equals("admin123")&&String.valueOf(pass1.getPassword()).equals("123")){
 
         this.setVisible(false);
        new AdminPanel().setVisible(true);   
            }
        else{
            try{
                String username = user.getText();
                String query = "select * from users where username=?";
                PreparedStatement ps = connect.prepareStatement(query);
                ps.setString(1,username);
                ResultSet rs = ps.executeQuery();       
                String password  = null;
                int count = 0;
                while(rs.next()){
                    count++;
                    password = rs.getString("password");
                    System.out.println(password);
                    type=rs.getInt("u_type");
                }
                if(count==1){
                    if(password.equals(String.valueOf(pass1.getPassword()))){
                        check = 1;
                    }else{
                        JOptionPane.showMessageDialog(null ,"Invalid Password!");
                    }
                }else{
                    JOptionPane.showMessageDialog(null ,"SORRY you need to register!");
                }
            }
            catch(Exception e){
            }
        }
        if(check==1){
          this.setVisible(false);
            if(type==0)
            new Booking(user.getText()).setVisible(true);
            else
             new Driver_login(user.getText()).setVisible(true);
        }
    }//GEN-LAST:event_loginActionPerformed

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        this.setVisible(false);
        new register().setVisible(true);
        //this.setVisible(true);
        
    }//GEN-LAST:event_signupActionPerformed

    private void pass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass1ActionPerformed

    private void userFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusGained
        if(user.getText().equals("Enter User ID")){
           user.setText(null);
           user.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_userFocusGained

    private void userFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userFocusLost
        if(user.getText().equals("")){
           user.setForeground(new Color(204,204,204));
           user.setText("Enter User ID");
        }
    }//GEN-LAST:event_userFocusLost

    private void pass1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusGained
        if(user.getText().equals("Enter Password")){
           user.setText(null);
           user.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_pass1FocusGained

    private void pass1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pass1FocusLost
        if(user.getText().equals("")){
           user.setForeground(new Color(0,0,0));
           user.setText("Enter Password");
        }
    }//GEN-LAST:event_pass1FocusLost

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JButton signup;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
